# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

target 'BTAssessmentSDKSampleAPP' do

  # pod 'BTAssessmentSDK', :path => "../BTAssessmentSDK/"
  pod 'BTAssessmentSDK', :git => 'https://github.com/bespot/assessment-sdk-ios', :tag => '1.0.3'

  # Pods for BTAssessmentSDKSampleAPP

  target 'BTAssessmentSDKSampleAPPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BTAssessmentSDKSampleAPPUITests' do
    # Pods for testing
  end

end
